### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by gtgrp-user** [HAAClassic/AdaTreeFormer#1]
I am currently working on training a model using AdaTreeFormer, but I have encountered some missing files:

- train.py and test.py: Fortunately, I was able to download these from the revision.

- rank_loss.py, consistency_loss.py, bregman_pytorch.py: I sourced these from TreeFormer.

- discriminator.py: I could not locate this file or find any reference to it.

- swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth: I also could not find a reference or source for this pre-trained model weight file.

Additionally, the following code snippet references `self.datasets` and `self.datasets_shot.` Am I correct in assuming that `self.datasets_shot` refers to the unlabeled datasets?

`self.datasets = {"train": Crowd_TC(os.path.join(args.data_dir, "train_data_100"), args.crop_size,
                downsample_ratio, "train"), "val": Crowd_TC(os.path.join(args.data_dir, "test_data"),
                args.crop_size, downsample_ratio, "val")}`
        
`self.datasets_shot = { "train": Crowd_TC(os.path.join(args.data_dir_ul, "train_data_01"), 
        args.crop_size, downsample_ratio, "train"),"val": Crowd_TC(os.path.join(args.data_dir_ul, "test_data"),
        args.crop_size, downsample_ratio, "val")}`

**Comment by HAAClassic** [comment]
Hi, I updated the files and tried to upload the missed files. 
The datasets_shot refers to the 5 shots. I modified the codes.
you can use the "https://towhee.readthedocs.io/en/branch0.9.0/_modules/towhee/models/swin_transformer/configs.html" for "swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth"

**Comment by gezixuan721-sys** [comment]
@gtgrp-user May I ask if you have successfully reproduced it?
