### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by Coperttaso** [HAAClassic/AdaTreeFormer#2]
Sir, I appreciate your work and am very interested in this research. Could you please provide me with a copy of test.py and train.py so that I can familiarize myself with it?  
E-mail: 19101999g@connect.polyu.hk
Thanks.

**Comment by heiheixixi3** [comment]
Sir, I am a collage student learning this subject. I appreciate your work and am very interested in this research. Could you please provide me with a copy of test.py and train.py so that I can familiarize myself with it?

E-mail: heiheixixi3@gmail.com
Thank you so much.

**Comment by HAAClassic** [comment]
Hi, I added them.

**Comment by gezixuan721-sys** [comment]
@Coperttaso @heiheixixi3 May I ask if you have successfully reproduced it?
